BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','BEARS');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','BEARS2');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CH08FAMILYTIES');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CH08HOUSE_REPAIR');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CH08IOTSURGERY');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CH08REPAIR_TYPE');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CH08SURGERY');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CLASSIFIED_AD');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CLASSIFIED_SECTION');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CLIENT');
END;
/
BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','CUSTOMER');
END;
/

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','EDITOR_REVENUE');
END;
/

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','EMPLOYEE');
END;
/

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','EXCEPTIONS');
END;
/

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE ('CLASSMATE','WANT_AD');
END;
/
