DROP TABLE CLASSMATE.CH08IOTSURGERY;
DROP TYPE CLASSMATE.PROCEDURES_ARRAY;
REM
CREATE TABLE CLASSMATE.CH08IOTSURGERY 
(SURGERY_ID NUMBER(10) NOT NULL, 
DOCTOR_NAME VARCHAR2(40) NOT NULL,
PATIENT_FISRT_NAME VARCHAR2(10) NOT NULL, 
PATIENT_LAST_NAME VARCHAR2(30) NOT NULL,
SURGERY_DATE DATE NOT NULL, 
PROCEDURES VARCHAR2(100) NOT NULL, 
CONSTRAINT SURGERY2_PK PRIMARY KEY(SURGERY_ID))
TABLESPACE USERS;
REM
CREATE TYPE CLASSMATE.PROCEDURES_ARRAY 
  AS VARRAY(15) OF CHAR(8)
/
REM
INSERT INTO CH08IOTSURGERY VALUES 
(1,'Dr. Sheriton-DeAngelos','Joe','Bailey',
'12-JAN-2004',0);
REM
INSERT INTO CH08IOTSURGERY VALUES 
(2,'Dr. Smith','Amy','South',
'14-JAN-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(3,'Dr. Angelo','Marge','Summers',
'15-JAN-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(4,'Dr. Sheriton-DeAngelos','Thomas','Blankenstone',
'30-MAY-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(5,'Dr. Angelo','Leroy','Brown',
'22-OCT-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(10,'Dr. Angelo','Marge','Summers',
'12-MAR-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(6,'Dr. Smith','Heather','Rain',
'11-FEB-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(42,'Dr. Angelo','Marge','Summers',
'05-JUL-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(7,'Dr. Angelo','Horace','Levins',
'12-APR-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(12,'Dr. Sheriton-DeAngelos','Bill','Holmes',
'01-MAR-2004',0);
INSERT INTO CH08IOTSURGERY VALUES 
(33,'Dr. Sheriton-DeAngelos','Martin','Lantern',
'11-SEP-2004',0);
COMMIT;